### ISSUE TITLE
Unable to clone

### ISSUE THREAD

**Issue by alvaro-osvaldo-tm** [iherwig/wcmf-default-app#5]
Following the Getting Started (http://wcmf.wemove.com/gettingstarted.html) after the clone (git clone .... ) the directory app/config don't exist ... Is it normal?

**Comment by iherwig** [comment]
The configuration (and other) files will be generated from the model when you execute the code generation step:

`ant generate`

You will need to have [Apache Ant](http://ant.apache.org/) (see [http://wcmf.wemove.com/gettingstarted.html#app_gen](http://wcmf.wemove.com/gettingstarted.html#app_gen)).

**Comment by iherwig** [comment]
Closing this, but feel free to follow up.
