### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by alvaro-osvaldo-tm** [iherwig/wcmf-default-app#6]
I'm created a new project by composer using composer.phar create-project wcmf/wcmf-default-app wcmf-default-app and created the file config/server.ini has described in http://wcmf.wemove.com/gettingstarted.html.

When I execute the install database script by http://localhost/wcmf-default-app/install/, nothing appears. In the server log I see:

> [Fri Mar 03 19:49:16.805145 2017] [:error] [pid 19033] [client 192.168.0.1:41926] PHP Fatal error:  Uncaught wcmf\\lib\\config\\ConfigurationException: Configuration file /srv/www/wcmf-default-app/app/config/config.ini not found! in /srv/www/wcmf-default-app/vendor/wcmf/wcmf/src/wcmf/lib/config/impl/InifileConfiguration.php:137\nStack trace:\n#0 /srv/www/wcmf-default-app/tools/database/install.php(37): wcmf\\lib\\config\\impl\\InifileConfiguration->addConfiguration('config.ini')\n#1 {main}\n  thrown in /srv/www/wcmf-default-app/vendor/wcmf/wcmf/src/wcmf/lib/config/impl/InifileConfiguration.php on line 137, referer: http://local.dev.php/wcmf-default-app/install/

So i renamed config/server.ini to config/config.ini and tried again.
And the browser return a message:

> [2017-03-03 19:49:52] INFO: install:44: initializing wCMF database tables... [2017-03-03 19:49:52] INFO: wcmf\lib\util\DBUtil:76: Executing SQL script /srv/www/wcmf-default-app/install/custom-install/database_1.sql ...

And stops ... in the apache error log I'm see 

> [Fri Mar 03 19:49:52.419802 2017] [:error] [pid 19036] [client 192.168.0.1:41930] PHP Fatal error:  Uncaught wcmf\\lib\\config\\ConfigurationException: Section 'persistenceFacade' not found! in /srv/www/wcmf-default-app/vendor/wcmf/wcmf/src/wcmf/lib/config/impl/InifileConfiguration.php:193\nStack trace:\n#0 /srv/www/wcmf-default-app/vendor/wcmf/wcmf/src/wcmf/lib/core/impl/DefaultFactory.php(121): wcmf\\lib\\config\\impl\\InifileConfiguration->getSection('persistenceFaca...')\n#1 /srv/www/wcmf-default-app/vendor/wcmf/wcmf/src/wcmf/lib/core/ObjectFactory.php(41): wcmf\\lib\\core\\impl\\DefaultFactory->getInstance('persistenceFaca...', Array)\n#2 /srv/www/wcmf-default-app/tools/database/install.php(59): wcmf\\lib\\core\\ObjectFactory::getInstance('persistenceFaca...')\n#3 {main}\n  thrown in /srv/www/wcmf-default-app/vendor/wcmf/wcmf/src/wcmf/lib/config/impl/InifileConfiguration.php on line 193, referer: http://local.dev.php/wcmf-default-app/install/

And the database still empty and http://localhost/wcmf-default-app/app/public/ it's not working.

**Comment by iherwig** [comment]
You will need to generate the missing files from the model (see http://wcmf.wemove.com/gettingstarted.html#app_gen). After that you can proceed with setting up the database connection in `server.ini`.

**Comment by iherwig** [comment]
Closing this, but feel free to follow up.
